apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-go-azure-020625 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=github-go-azure-020625
    backstage.io/kubernetes-id: github-go-azure-020625 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: rhtap-qe-jsmid/github-go-azure-020625
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: rhtap-qe-jsmid.github-go-azure-020625
    quay.io/repository-slug: jsmid/rhtap-qe-jsmid
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 